export const movieOptions = [{"name":"Robin, white-throated"},
{"name":"Bird (unidentified)"},
{"name":"Common grenadier"},
{"name":"American crow"},
{"name":"Possum, ring-tailed"},
{"name":"Red-billed toucan"},
{"name":"Tern, white-winged"},
{"name":"Potoroo"},
{"name":"Cat, ringtail"},
{"name":"Koala"},
{"name":"Wild boar"},
{"name":"Crown of thorns starfish"},
{"name":"Racer snake"},
{"name":"Yellow baboon"},
{"name":"Egyptian viper"},
{"name":"Hawk, galapagos"},
{"name":"Green-winged trumpeter"},
{"name":"Stork, white-necked"},
{"name":"Land iguana"},
{"name":"Hoopoe, eurasian"},
{"name":"Common rhea"},
{"name":"Heron, grey"},
{"name":"Killer whale"},
{"name":"Hawk-eagle, crowned"},
{"name":"Springbok"},
{"name":"Snake, buttermilk"},
{"name":"Agama lizard (unidentified)"},
{"name":"Rat, arboral spiny"},
{"name":"American woodcock"},
{"name":"Wallaby, whip-tailed"},
{"name":"Eastern indigo snake"},
{"name":"Blue-breasted cordon bleu"},
{"name":"Grey mouse lemur"},
{"name":"Deer, spotted"},
{"name":"Squirrel, european red"},
{"name":"Dog, african wild"},
{"name":"Langur, hanuman"},
{"name":"Northern elephant seal"},
{"name":"White-faced whistling duck"},
{"name":"Wildebeest, blue"},
{"name":"Vulture, turkey"},
{"name":"Arctic ground squirrel"},
{"name":"Tiger snake"},
{"name":"Penguin, galapagos"},
{"name":"Little cormorant"},
{"name":"Kookaburra, laughing"},
{"name":"Mandras tree shrew"},
{"name":"Paradoxure"},
{"name":"Burrowing owl"},
{"name":"Vulture, white-headed"},
{"name":"Crow, pied"},
{"name":"Thomson's gazelle"},
{"name":"Snake, racer"},
{"name":"Dragon, komodo"},
{"name":"Red-tailed phascogale"},
{"name":"Pelican, brown"},
{"name":"Springhare"},
{"name":"King cormorant"},
{"name":"Burchell's gonolek"},
{"name":"Gila monster"},
{"name":"Arboral spiny rat"},
{"name":"Dog, african wild"},
{"name":"Squirrel, richardson's ground"},
{"name":"Spotted hyena"},
{"name":"Marten, american"},
{"name":"Squirrel, uinta ground"},
{"name":"Turtle, long-necked"},
{"name":"Spotted hyena"},
{"name":"Scottish highland cow"},
{"name":"Klipspringer"},
{"name":"Stork, greater adjutant"},
{"name":"Macaque, japanese"},
{"name":"Short-nosed bandicoot"},
{"name":"Brown hyena"},
{"name":"Lizard, collared"},
{"name":"Viper, egyptian"},
{"name":"Duiker, gray"},
{"name":"Columbian rainbow boa"},
{"name":"Eastern dwarf mongoose"},
{"name":"Boa, columbian rainbow"},
{"name":"Rock dove"},
{"name":"Red and blue macaw"},
{"name":"Pronghorn"},
{"name":"Seal, southern elephant"},
{"name":"Dove, ring"},
{"name":"Legaan, water"},
{"name":"Saddle-billed stork"},
{"name":"Agama lizard (unidentified)"},
{"name":"Red phalarope"},
{"name":"Agile wallaby"},
{"name":"Goldeneye, common"},
{"name":"Boa, mexican"},
{"name":"Crested bunting"},
{"name":"Galapagos sea lion"},
{"name":"Glossy starling (unidentified)"},
{"name":"Finch, common melba"},
{"name":"Galapagos hawk"},
{"name":"Blacksmith plover"},
{"name":"Jackal, asiatic"},
{"name":"Silver-backed jackal"}];